# Uncomment the next line to define a global platform for your project
platform :osx, '12.0'

# 指定 Xcode 项目
project 'PreviewMacApp.xcodeproj'

target 'KuiklyUITools' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Kuikly iOS Render Core
  pod 'OpenKuiklyIOSRender', :path => '../'
  
  # 图片加载
  pod 'SDWebImage'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

